class_3_col <- "col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-xs-12"


# Component Builders ------------------------------------------------------

two_column_flips_on_mobile <- function(left, right, override_width_classes = TRUE) {
  
  left_col_class <- "col-sm-12 col-md-pull-6 col-md-6 col-lg-5 col-lg-pull-7"
  right_col_class <- "col-sm-12 col-md-push-6 col-md-6 col-lg-7 col-lg-push-5"
  
  if (!override_width_classes) {
    right <- tags$div(class = right_col_class, right)
    left  <- tags$div(class = left_col_class,  left)
  } else {
    strip_col_class <- function(x) gsub("col-(xs|sm|md|lg)-\\d{1,2}\\s*", "", x)
    left$attrib$class  <- strip_col_class(left$attrib$class)
    right$attrib$class <- strip_col_class(right$attrib$class)
    
    left$attrib$class  <- paste(left$attrib$class,  left_col_class)
    right$attrib$class <- paste(right$attrib$class, right_col_class)
  }
  
  fluidRow(right, left)
}


# Components --------------------------------------------------------------

components <- list(toolbar = list())

# Components - Clickpad ----
components$toolbar$clickpad_action <- tags$div(
  radioSwitchButtons(
    "clickpad_click_action",
    HTML(paste(icon("mouse-pointer"), "Click a node to...")),
    choices = c("Select" = "parent", "Draw/Remove Edge" = "child"),
    selected = "parent",
    selected_background = "#D3751C"
  )
)

# Components - Node List ----
components$toolbar$node_list_actions <- tags$div(
  class = "btn-toolbar",
  role = "toolbar",
  tags$form(
    class = "form-inline",
    tags$div(
      class = "form-group",
      tags$div(
        class = "btn-group",
        role = "group",
        actionButton(
          input = "node_list_node_add", 
          label = "Add New Node", 
          icon = icon("plus"),
          alt = "Add New Node to Workspace",
          `data-toggle` = "tooltip",
          `data-placement` = "bottom",
          title = "Add New Node to Workspace"
        ),
        shinyjs::hidden(
          actionButton(
            "node_list_node_delete", "Delete Node", icon("trash"),
            alt = "Delete Node",
            `data-toggle` = "tooltip",
            `data-placement` = "bottom",
            title = "Delete Node")
        )
      )
    )
  )
)

components$toolbar$node_list_name <- tags$div(
  style = "padding-top: 15px; min-height: 90px;",
  shinyjs::hidden(
    tags$div(
      id = "node_list_node_name_container",
      class = "col-xs-12",
      textInput("node_list_node_name", "Node Name", width = "100%")
    )
  )
)

# Components - About ----
components$about <- tagList(
  h4("Development Team: Jordan Creed, Travis Gerke, and Garrick Aden-Buie"),
  p(
    "For more information on our lab and other projects please check",
    "out our website at",
    tags$a(href = "http://gerkelab.com", "gerkelab.com")
  ),
  p(
    "All code is available on GitHub at",
    tags$a(
      href = "https://github.com/GerkeLab/ShinyDAG",
      "GerkeLab/ShinyDag"
    )
  ),
  p(
    "Any errors or comments can be directed to",
    tags$a(href = "mailto:travis.gerke@moffitt.org", "travis.gerke@moffitt.org"),
    "or",
    tags$a(href = "mailto:jordan.h.creed@moffitt.org", "jordan.h.creed@moffitt.org")
  )
)

# Components - Build ----
components$build <- box(
  title = "Build",
  id = "build-box",
  width = 12,
  fluidRow(
    id = "shinydag-toolbar",
    tags$div(
      class = "col-xs-12 col-md-5 shinydag-toolbar-actions",
      tags$div(
        class = "col-xs-12 col-sm-6 col-md-12",
        id = "shinydag-toolbar-node-list-action",
        components$toolbar$node_list_action
      ),
      tags$div(
        class = "col-xs-12 col-sm-6 col-md-12",
        style = "padding: 10px",
        id = "shinydag-toolbar-clickpad-action",
        components$toolbar$clickpad_action
      )
    ),
    tags$div(
      class = "col-xs-12 col-md-7",
      components$toolbar$node_list_name
    )
  ),
  fluidRow(column(width = 12, uiOutput("node_list_helptext"))),
  fluidRow(
    column(
      width = 12,
      clickpad_UI("clickpad", height = "600px", width = "100%")
    )
  ),
  fluidRow(
    tags$div(
      class = class_3_col,
      shinyjs::disabled(
        selectInput("exposureNode", "Exposure", choices = c("None" = ""), width = "100%")
      )
    ),
    tags$div(
      class = class_3_col,
      shinyjs::disabled(
        selectInput("outcomeNode", "Outcome", choices = c("None" = ""), width = "100%")
      )
    ),
    tags$div(
      class = class_3_col,
      shinyjs::disabled(
        selectizeInput("adjustNode", "Adjust for...", choices = c("None" = ""), width = "100%", multiple = TRUE)
      )
    )
  ),
  fluidRow(
    tags$div(
      class = "col-sm-12",
      uiOutput("openExpOutcomePaths")
    )
  )
)

# Components - LaTeX ----
components$latex <- tagList(
  tags$p(
    "Use this tab to manually edit the TikZ generated by shinyDAG."
  ),
  helpText(
    "Note that changes made to the TikZ code below will not affect",
    "the DAG settings in the app. Changes made to the DAG elsewhere",
    "in shinyDAG will overwrite any changes made to the manually",
    "edited TikZ code below."
  ),
  uiOutput("texEdit")
)

# Components - Tweak ----
components$tweak <- tabBox(
  title = "Edit DAG",
  id = "tab_control",
  # ---- Tab: Edit Aesthetics
  tabPanel(
    "Edit aesthetics",
    value = "edit_edge_aesthetics",
    selectInput(
      "arrowShape",
      "Select arrow head",
      choices = c(
        "stealth",
        "stealth'",
        "diamond",
        "triangle 90",
        "hooks",
        "triangle 45",
        "triangle 60",
        "hooks reversed",
        "*"
      ),
      selected = "stealth"
    ),
    uiOutput("edge_aes_ui")
  )
)

# UI - shinyDAG -----------------------------------------------------------

function(request) {
  dashboardPage(
    title = "shinyDAG",
    skin = "black",
    dashboardHeader(
      title = "shinyDAG",
      tags$li(
        class = "dropdown",
        actionLink(
          inputId = "._bookmark_", 
          label = "Bookmark",
          icon = icon("link", lib = "glyphicon"),
          title = "Bookmark ShinyDAG's state and get a URL for sharing.",
          `data-toggle` = "tooltip",
          `data-placement` = "bottom"
        )
      ),
      tags$li(
        class = "dropdown",
        tags$a(
          href = "https://github.com/gerkelab/shinyDAG/",
          title = "shinyDAG on GitHub",
          target = "_blank",
          icon("github")
        )
      ),
      tags$li(
        class = "dropdown",
        tags$a(
          href = "https://gerkelab.com/project/shinyDAG/",
          title = "GerkeLab Project Page",
          target = "_blank",
          icon("flask")
        )
      )
    ),
    dashboardSidebar(
      sidebarMenu(
        menuItem("Sketch", tabName = "sketch", icon = icon("share-alt")),
        menuItem("Tweak", tabName = "tweak", icon = icon("sliders")),
        menuItem("LaTeX", tabName = "latex", icon = icon("file-text-o")),
        menuItem("About", tabName = "about", icon = icon("info")),
        tags$a(
          href = "https://gerkelab.com", 
          target = "_blank", 
          tags$div(class = "gerkelab-logo")
        )
      )
    ),
    dashboardBody(
      shinyjs::useShinyjs(),
      tags$script(src = "shinydag.js", async = TRUE),
      includeCSS("www/AdminLTE.gerkelab.min.css"),
      includeCSS("www/_all-skins.gerkelab.min.css"),
      includeCSS("www/shinydag.css"),
      chooseSliderSkin("Flat", "#418c7a"),
      tags$a(
        href = "https://gerkelab.com", 
        target = "_blank", 
        tags$div(class = "gerkelab-logo")
      ),
      tabItems(
        tabItem(
          tabName = "sketch",
          components$build
        ),
        tabItem(
          tabName = "tweak",
          two_column_flips_on_mobile(
            components$tweak,
            box(
              title = "Preview DAG",
              dagPreviewUI("tweak_preview", include_graph_downloads = TRUE)
            )
          )
        ),
        tabItem(
          tabName = "latex",
          two_column_flips_on_mobile(
            box(
              title = "Edit LaTeX",
              components$latex
            ),
            box(
              title = "Preview LaTeX",
              dagPreviewUI("latex_preview", include_graph_downloads = FALSE)
            )
          )
        ),
        tabItem(
          tabName = "about",
          box(
            title = "About ShinyDAG",
            width = 12,
            components$about
          )
        )
      )
    )
  )
}
