class_3_col <- "col-md-4 col-md-offset-0 col-sm-8 col-sm-offset-2 col-xs-12"

# UI ----------------------------------------------------------------------

components <- list(toolbar = list())

components$toolbar$clickpad_action <- tags$div(
  radioSwitchButtons(
    "clickpad_click_action",
    HTML(paste(icon("mouse-pointer"), "Click a node to...")),
    choices = c("Select" = "parent", "Draw/Remove Edge" = "child"),
    selected = "parent",
    selected_background = "#D3751C"
  )
)

components$toolbar$node_list_actions <- tags$div(
  class = "btn-toolbar",
  role = "toolbar",
  tags$form(
    class = "form-inline",
    tags$div(
      class = "form-group",
      tags$div(
        class = "btn-group",
        role = "group",
        actionButton(
          input = "node_list_node_add", 
          label = "Add New Node", 
          icon = icon("plus"),
          alt = "Add New Node to Workspace",
          `data-toggle` = "tooltip",
          `data-placement` = "bottom",
          title = "Add New Node to Workspace"
        ),
        shinyjs::hidden(
          actionButton(
            "node_list_node_delete", "Delete Node", icon("trash"),
            alt = "Delete Node",
            `data-toggle` = "tooltip",
            `data-placement` = "bottom",
            title = "Delete Node")
        )
      )
    )
  )
)

components$toolbar$node_list_name <- tags$div(
  style = "padding-top: 15px; min-height: 90px;",
  shinyjs::hidden(
    tags$div(
      id = "node_list_node_name_container",
      class = "col-xs-12",
      textInput("node_list_node_name", "Node Name", width = "100%")
    )
  )
)

components$about <- tagList(
  h4("Development Team: Jordan Creed, Travis Gerke, and Garrick Aden-Buie"),
  p(
    "For more information on our lab and other projects please check",
    "out our website at",
    tags$a(href = "http://gerkelab.com", "gerkelab.com")
  ),
  p(
    "All code is available on GitHub at",
    tags$a(
      href = "https://github.com/GerkeLab/ShinyDAG",
      "GerkeLab/ShinyDag"
    )
  ),
  p(
    "Any errors or comments can be directed to",
    tags$a(href = "mailto:travis.gerke@moffitt.org", "travis.gerke@moffitt.org"),
    "or",
    tags$a(href = "mailto:jordan.h.creed@moffitt.org", "jordan.h.creed@moffitt.org")
  )
)

components$build <- box(
  title = "Build",
  id = "build-box",
  width = 12,
  fluidRow(
    id = "shinydag-toolbar",
    tags$div(
      class = "col-xs-12 col-md-5 shinydag-toolbar-actions",
      tags$div(
        class = "col-xs-12 col-sm-6 col-md-12",
        id = "shinydag-toolbar-node-list-action",
        components$toolbar$node_list_action
      ),
      tags$div(
        class = "col-xs-12 col-sm-6 col-md-12",
        style = "padding: 10px",
        id = "shinydag-toolbar-clickpad-action",
        components$toolbar$clickpad_action
      )
    ),
    tags$div(
      class = "col-xs-12 col-md-7",
      components$toolbar$node_list_name
    )
  ),
  fluidRow(column(width = 12, uiOutput("node_list_helptext"))),
  fluidRow(
    column(
      width = 12,
      clickpad_UI("clickpad", height = "600px", width = "100%")
    )
  ),
  fluidRow(
    tags$div(
      class = class_3_col,
      shinyjs::disabled(
        selectInput("exposureNode", "Exposure", choices = c("None" = ""), width = "100%")
      )
    ),
    tags$div(
      class = class_3_col,
      shinyjs::disabled(
        selectInput("outcomeNode", "Outcome", choices = c("None" = ""), width = "100%")
      )
    ),
    tags$div(
      class = class_3_col,
      shinyjs::disabled(
        selectizeInput("adjustNode", "Adjust for...", choices = c("None" = ""), width = "100%", multiple = TRUE)
      )
    )
  ),
  fluidRow(
    tags$div(
      class = "col-sm-12",
      uiOutput("openExpOutcomePaths")
    )
  )
)

components$latex <- tagList(
  tags$p(
    "Use this tab to manually edit the TikZ generated by shinyDAG."
  ),
  helpText(
    "Note that changes made to the TikZ code below will not affect",
    "the DAG settings in the app. Changes made to the DAG elsewhere",
    "in shinyDAG will overwrite any changes made to the manually",
    "edited TikZ code below."
  ),
  uiOutput("texEdit")
)


function(request) {
  dashboardPage(
    title = "shinyDAG",
    skin = "black",
    dashboardHeader(
      title = "shinyDAG",
      tags$li(
        class = "dropdown",
        tags$a(
          href = "https://github.com/gerkelab/shinyDAG/",
          title = "shinyDAG on GitHub",
          target = "_blank",
          icon("github")
        )
      ),
      tags$li(
        class = "dropdown",
        tags$a(
          href = "https://gerkelab.com/project/shinyDAG/",
          title = "GerkeLab Project Page",
          target = "_blank",
          icon("flask")
        )
      )
    ),
    dashboardSidebar(
      sidebarMenu(
        menuItem("Sketch", tabName = "sketch", icon = icon("share-alt")),
        menuItem("Tweak", tabName = "tweak", icon = icon("sliders")),
        menuItem("LaTeX", tabName = "latex", icon = icon("file-text-o")),
        menuItem("About", tabName = "about", icon = icon("info")),
        tags$a(
          href = "https://gerkelab.com", 
          target = "_blank", 
          tags$div(class = "gerkelab-logo")
        )
      )
    ),
    dashboardBody(
      shinyjs::useShinyjs(),
      tags$script(src = "shinydag.js", async = TRUE),
      includeCSS("www/AdminLTE.gerkelab.min.css"),
      includeCSS("www/_all-skins.gerkelab.min.css"),
      includeCSS("www/shinydag.css"),
      chooseSliderSkin("Flat", "#418c7a"),
      tags$a(
        href = "https://gerkelab.com", 
        target = "_blank", 
        tags$div(class = "gerkelab-logo")
      ),
      tabItems(
        tabItem(
          tabName = "sketch",
          components$build
        ),
        tabItem(
          tabName = "tweak",
          fluidRow(
            tabBox(# ---- Box: Controls ----
                   title = "Edit DAG",
                   width = "12 col-md-push-6 col-md-6 col-lg-7 col-lg-push-5",
                   id = "tab_control",
                   # # ---- Tab: Build ----
                   
                   # ---- Tab: Edit Aesthetics ----
                   tabPanel(
                     "Edit aesthetics",
                     value = "edit_edge_aesthetics",
                     selectInput(
                       "arrowShape",
                       "Select arrow head",
                       choices = c(
                         "stealth",
                         "stealth'",
                         "diamond",
                         "triangle 90",
                         "hooks",
                         "triangle 45",
                         "triangle 60",
                         "hooks reversed",
                         "*"
                       ),
                       selected = "stealth"
                     ),
                     uiOutput("edge_aes_ui")
                   )
            ),
            box( # ---- Box: DAG ----
                 title = "Preview DAG",
                 width = "12 col-md-pull-6 col-md-6 col-lg-5 col-lg-pull-7",
                 column(
                   width = 12, 
                   align = "center", 
                   shinyjs::hidden(tags$div(
                     id = "tikzOut-help",
                     class="alert alert-danger",
                     role="alert",
                     HTML(
                       "<p>An error occurred while compiling the preview.",
                       "Are there syntax errors in your labels?",
                       "Single <code>$</code> need to be escaped: <code>\\$</code>.</p>"
                     )
                   )),
                   uiOutput("tikzOut")
                 ),
                 fluidRow(
                   tags$div(
                     class = class_3_col,
                     tags$div(
                       id = "showPreviewContainer",
                       prettySwitch("showPreview", "Preview DAG", status = "primary", fill = TRUE),
                       uiOutput("showPreview_helptext")
                     )
                   ),
                   tags$div(
                     class = class_3_col,
                     selectInput(
                       "downloadType",
                       "Type of download",
                       choices = list(
                         "PDF" = "pdf",
                         "PNG" = "png",
                         "LaTeX TikZ" = "tikz",
                         "dagitty (R: RDS)" = "dagitty",
                         "ggdag (R: RDS)" = "ggdag"
                       )
                     ),
                     uiOutput("downloadType_helptext")
                   ),
                   tags$div(
                     class = class_3_col,
                     div(
                       class = "btn-group",
                       role = "group",
                       id = "download-buttons",
                       downloadButton("downloadButton"),
                       bookmarkButton(label = "Bookmark")
                     )
                   )
                 )
            ) # DAG box ends ----
          )
        ),
        tabItem(
          tabName = "latex",
          box(
            title = "LaTeX",
            width = 12, 
            components$latex
          )
        ),
        tabItem(
          tabName = "about",
          box(
            title = "About ShinyDAG",
            width = 12,
            components$about
          )
        )
      )
    )
  )
}
